mini/hospital/urls.py
from django.conf.urls import url
from django.urls import path

from hospital.views import *

app_name = 'hospital'

urlpatterns = [
    #hospital/
    path('', InfoLV.as_view(), name='index'),
    #hospital/patient
    path('patient/', InfoLV.as_view(), name='patient_list'),
    #hospital/patient/detail
    path('patient/<int:pid>', InfoDV.as_view(), name='patient_detail'),
    #/search/
    path('search/', SearchFormView.as_view(), name='search'),
    path('append/', InfoCreateView.as_view(), name = 'append'),
]

mini/mini/urls.py
from django.contrib import admin
from django.urls import path, include 

from mini.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('hospital/', include('hospital.urls')),
    path('patient/', include('patient.urls')),
]

mini/patient/urls.py
from django.urls import path
from patient import views
app_name='patient'
urlpatterns = [
    # path('', views.file_list_all, name='file_list'),
    path('file/', views.file_list_all, name='file_list'),
    path('file/download/', views.file_download, name='file_download'),
    path('<int:patient_pid>/file/', views.file_list, name='file_list'),
    # path('<int:patient_id>/file/download/', views.file_download, name='file_download'),

    path('file/add/', views.file_edit, name='file_add'),
]

mini/hospital/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Info(models.Model):
    name = models.CharField('NAME', max_length=50)
    pid = models.IntegerField('Patient ID', unique=True, blank=True, null=True)
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, null=True)
    content = models.TextField('CONTENT')
    createDate = models.DateTimeField('Create Date', auto_now_add=True)
    modifyDate = models.DateTimeField('Modify Date', auto_now=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'info'
        verbose_name_plural = 'infos'
        db_table = 'hospital_patients'
        ordering = ('-modifyDate',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('hospital:info_detail', args=(self.slug,))

    def get_preivous_info(self):
        return self.get_previous_by_modifyDate()

    def get_next_info(self):
        return self.get_next_by_modifyDate()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name, allow_unicode=True)
        super(Info, self).save(*args, **kwargs)

mini/hospital/forms.py
from django import forms

class InfoSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

mini/hospital/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView
from django.db.models import Q
from django.urls import reverse_lazy

from hospital.models import Info
from hospital.forms import InfoSearchForm, UploadFileForm
from mini.views import LoginRequiredMixin

# Create your views here.
class InfoLV(ListView):
    model = Info
    template_name = 'hospital/info_all.html'
    context_object_name = 'infos'

    paginate_by = 5

class InfoDV(DetailView):
    model = Info

class SearchFormView(FormView):
    form_clas = InfoSearchForm
    template_name = 'hospital/info_search.html'
    
    def form_vaild(self, form):
        schWord = '%s' % self.request.post['search_word']

        info_list = Info.objects.filter(Q(name__icontains=schWord) |
                Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_keyword'] = schWord
        context['search_list'] = info_list

class InfoCreateView(LoginRequiredMixin, CreateView):
    models = Info
    fields = ['name', 'pid', 'description','content' ]
    initial = {'pid': 'auto-filling-by-title'}
    success_url = reverse_lazy('hospital:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(InfoCreateView,self).form_valid(form)

class upload_file():
    pass

mini/hospital/templates/hospital/base.html
{% load i18n static %}
<!DOCTYPE html> {% get_current_language as LANGUAGE_CODE %}
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'patient/css/bootstrap.min.css' %}"> {% block extra_css %}{% endblock %}
    <title>{% block title %}My Files{% endblock %}</title>
</head>

<body>
    <div class="container">
        {% block content %} {{ content }} {% endblock %}
    </div>
    <script src="{% static 'cms/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script> {% block extra_js%}{% endblock %}
</body>

</html>

mini/hospital/templates/hospital/file_download.html
<html>

<head>

</head>

<body>
    <div>"hi"</div>
</body>

</html>

mini/hospital/templates/hospital/file_edit.html
{% extends "hospital/base.html" %} {% load bootstrap4 %} {% block title %}파일 추가/수정{% endblock title%} {% block content %}
<h4 class="mt-4 mb-5 border-bottom">파일 추가/수정</h4>
{% if file_id %}
<form action="{% url 'patient:file_modify' file_id=file_id %}" method="post">
    {% else %}
    <form action="{% url 'patient:file_add' %}" method="post">
        {% endif %} {% csrf_token %} {% bootstrap_form form layout='horizontal' %}

        <div class="form-group row">
            <div class="offset-md-3 col-md-9">
                <button type="buttom" class="btn btn-primary">전송</button>
            </div>
        </div>
    </form>

    <a href="" class="btn btn-secondary btn-sm">돌아가기</a>
    {% endblock content %}

mini/hospital/templates/hospital/file_list.html
{% extends "hospital/base.html" %} {% block title %}파일 목록{% endblock %} {% block content %}
<h4 class="mt-4 border-bottom"> 파일 목록</h4>
<a href="{% url 'hospital:file_add' %}" class="btn btn-primary btn-sm my-3">추가</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">파일명</th>
            <th scope="col">파일</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for file in files %}
        <tr>
            <th scope="row">{{ file.id }}</th>
            <td>{{ file.file_name }}</td>
            <td>{{ file.file_file }}</td>
            <td>
                <a href="{% url 'hospital:file_download' file_id=file.id %}" class="btn btn-outline-primary btn-sm">다운로드</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

mini/hospital/templates/hospital/info_all.html
{% block title %}전체 정보{% endblock%}
{% load staticfiles %}
{% block content %}
<div id="content">
    <h1>Patient Info List</h1>

    <!-- display info list -->
    {% for info in infos %}
        <h2><a href="{{ post.get_absolute_url }}">{{ info.name }}</a></h2>
        {{ info.modifyDate|date:"N d, Y"}}
        <p>{{ info.description }}</p>
    {% endfor %}

    <br/>

    <!-- paging link -->
    <div style="position:relative;height: 20px;">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">
                    <img src="{% static 'img/left.png' %}" style="position:relative;top:3px;width:18px; height:18px;"/></a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} 

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">
                    <img src="{% static 'img/right.png' %}" style="position:relative;top:3px;width:18px; height:18px;"/></a>
        {% endif %}
    </div>

</div>
{% endblock %}

mini/hospital/templates/hospital/info_detail.html
{% block title %}정보 상세보기{% endblock%}
{% block content %}
<div id="content">
<h2>{{ object.name }}</h2>

<!-- previous or next post link -->
<p class="other_posts">
    <a href="{{ object.get_previous_post.get_absolute_url }}">
        {{ object.get_previous_post }}
    </a>
    |
    <a href="{{ object.get_next_post.get_absolute_url }}">
        {{ object.get_next_post }}
    </a>
</p>

<!-- date -->
<p class="date">
    {{ object.modifyDate|date:"j F Y" }}
</p>
<br/>
<!-- info content -->
<div class="body">
    {{ object.content|linebreaks }}
</div>
</div>
{% endblock %}

mini/hospital/templates/hospital/info_form.html

{% block title %}Info 생성 페이지{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Info Create/Update - {{ user }} </h1>
    <form action="." method="post">
        {% csrf_token %}

        {% if form.errors %}
            {{ form.errors }}
        {% endif %}

        <p>등록(수정)하고 싶은 Info를 작성해 주세요.</p>
        <fieldset class="aligned">
            <div class="form-row">
                {{form.name.label_tag}} {{form.name}}
            </div>
            <div class="form-row">
                {{form.pid.label_tag}} {{form.pid}}
            </div>
            <div class="form-row">
                {{form.description.label_tag}} {{form.description}}
            </div>
            <div class="form-row">
                {{form.content.label_tag}} {{form.content}}
            </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="등록" />
        </div>
    </form>
</div>
{% endblock %}

mini/hospital/templates/hospital/info_search.html
{% block title %} 검색 페이지 {% endblock %}

{% block content %}
<div id="content">
    <h1>Info Search Engine</h1>

    <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="text" name="search_word" value="{{ search_keyword }}">
        <input type="submit" value="Search" />
    </form>

    <br/><br/>
    
    {% if search_list %}
        {% for info in search_list %}
            <h2>{{ info.name }}</h2>
            {{ info.modifyDate|date:"Y-m-d" }}
            <p>{{ info.description }}</p>
        {% endfor %}
    {% elif search_keyword %}
        [{{ search_keyword }}]의 검색 결과가 없습니다.
    {% endif %}
</div>
{% endblock %}