mini/mini/urls.py
from django.contrib import admin
from django.urls import path, include 

from mini.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('hospital/', include('hospital.urls')),
    path('patient/', include('patient.urls')),
]

mini/patient/urls.py
from django.urls import path
from patient import views
app_name='patient'
urlpatterns = [
    # path('', views.file_list_all, name='file_list'),
    path('file/', views.file_list_all, name='file_list'),
    path('file/download/', views.file_download, name='file_download'),
    path('<int:patient_pid>/file/', views.file_list, name='file_list'),
    # path('<int:patient_id>/file/download/', views.file_download, name='file_download'),

    path('file/add/', views.file_edit, name='file_add'),
]

mini/patient/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Info(models.Model):
    name = models.CharField('NAME', max_length=50)
    pid = models.IntegerField('Patient ID', blank=True, null=True)
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, null=True)
    content = models.TextField('CONTENT')
    createDate = models.DateTimeField('Create Date', auto_now_add=True)
    modifyDate = models.DateTimeField('Modify Date', auto_now=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='%(class)s_patient_models')

mini/patient/forms.py
# /cms/templates/forms.py
from django.forms import ModelForm
from patient.models import Info

class FileForm(ModelForm):
    class Meta:
        model = Info
        fields = ('name', 'pid', 'description', 'content', 'owner',)

mini/patient/views.py
from django.shortcuts import render,get_object_or_404,get_list_or_404,redirect
from django.http import HttpResponse
from patient.models import Info
from patient.forms import FileForm
# Create your views here.	# Create your views here.

def file_list_all(request):
    files=Info.objects.order_by('pid')
    context={}
    context['files']=files

    return render(request,'patient/file_list.html',context)

def file_download(request):
    return HttpResponse('파일 다운로드')

def file_list(request,patient_pid):
    # files=get_object_or_404(Info)
    # files=Info.objects.get(pk=patient_pid)
    # files=Info.objects.order_by('id')
    # files=Info.objects.all()
    files=get_list_or_404(Info,pid=patient_pid)
    context={}
    context['files']=files

    return render(request,'patient/file_list.html',context)

# def file_download(request, patient_id):
#     context={}
#     if patient_id:
#         files = get_object_or_404(Info,pk=patient_id)
#         context['files']=files
#     else:
#         return render(request, 'patient/file_list.html',context)
#     return HttpResponse('파일 다운로드')

def file_edit(request, file_id=None):
    if file_id:
        files=get_object_or_404(Info,pk=file_id)
    else:
        files=Info()
    
    if request.method == 'POST':
        form=FileForm(request.POST,instance=files)
        if form.is_valid():
            files=form.save(commit=False)
            files.save()
            return redirect('patient:file_list')
    else:
        form=FileForm(instance=files)
        return render(request, 'patient/file_edit.html',dict(form=form, file_id=file_id))

mini/patient/templates/patient/base.html
{% load i18n static %}
<!DOCTYPE html> {% get_current_language as LANGUAGE_CODE %}
<html>
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'patient/css/bootstrap.min.css' %}"> {% block extra_css %}{% endblock %}
    <title>{% block title %}My Files{% endblock %}</title>
</head>
 <body>
    <div class="container">
        {% block content %} {{ content }} {% endblock %}
    </div>
    <script src="{% static 'cms/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script> {% block extra_js%}{% endblock %}
</body>
 </html

mini/patient/templates/patient/file_download.html
<html>
    <head>

    </head>
    <body>
        <div>"hi"</div>
    </body>
</html> 

mini/patient/templates/patient/file_edit.html
{% extends "patient/base.html" %}
{% load bootstrap4 %}

{% block title %}파일 추가/수정{% endblock title%}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">파일 추가/수정</h4>
 {% if file_id %}
    <!-- <form action="{% url 'patient:file_modify' book_id=book_id %}" method="post"> -->
 {% else %}
    <form action="{% url 'patient:file_add' %}" method="post">
 {% endif %}
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}

        <div class="form-group row">
            <div class="offset-md-3 col-md-9">
                <button type="buttom" class="btn btn-primary">전송</button>
            </div>
        </div>
    </form>

    <a href="" class="btn btn-secondary btn-sm">돌아가기</a>
{% endblock content %}

mini/patient/templates/patient/file_list.html
{% extends "patient/base.html" %} {% block title %}파일 목록{% endblock %} {% block content %}
<h4 class="mt-4 border-bottom"> 파일 목록</h4>
<a href="{% url 'patient:file_add' %}" class="btn btn-primary btn-sm my-3">추가</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">PID</th>
            <th scope="col">파일명</th>
            <th scope="col">파일</th>
            <th scope="col"></th>
        </tr>
    </thead>
<tbody>
    {% for file in files %}
    <tr>
        <th scope="row">{{ file.id }}</th>
            <td>{{ file.pid }}</td>
            <td>{{ file.name }}</td>
            <td>{{ file.description }}</td>
            <td>
                <a href="{% url 'patient:file_download' %}" class="btn btn-outline-primary btn-sm">다운로드</a>
            </td>
        </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %} 